# Generated by Django 5.2.1 on 2025-10-15 22:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0002_booking_payment_deadline_booking_payment_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Số tiền thanh toán (VND)', max_digits=12)),
                ('currency', models.CharField(default='VND', max_length=3)),
                ('payment_method', models.CharField(choices=[('vnpay', 'VNPay'), ('cash', 'Tiền mặt'), ('bank_transfer', 'Chuyển khoản')], default='vnpay', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('processing', 'Đang xử lý'), ('completed', 'Đã thanh toán'), ('failed', 'Thanh toán thất bại'), ('cancelled', 'Đã hủy'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=20)),
                ('vnpay_transaction_id', models.CharField(blank=True, help_text='Mã giao dịch VNPay', max_length=50, null=True)),
                ('vnpay_order_id', models.CharField(blank=True, help_text='Mã đơn hàng VNPay', max_length=50, null=True)),
                ('vnpay_response_code', models.CharField(blank=True, help_text='Mã phản hồi VNPay', max_length=10, null=True)),
                ('vnpay_secure_hash', models.CharField(blank=True, help_text='Chữ ký VNPay', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Thời gian thanh toán thành công', null=True)),
                ('expired_at', models.DateTimeField(blank=True, help_text='Thời gian hết hạn thanh toán', null=True)),
                ('description', models.TextField(blank=True, help_text='Mô tả giao dịch')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP của người thanh toán', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent của người thanh toán')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='booking.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Hành động: created, paid, failed, etc.', max_length=50)),
                ('message', models.TextField(help_text='Thông điệp log')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Dữ liệu bổ sung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payment.payment')),
            ],
            options={
                'verbose_name': 'Log thanh toán',
                'verbose_name_plural': 'Log thanh toán',
                'ordering': ['-created_at'],
            },
        ),
    ]
