# Generated by Django 5.2.1 on 2025-10-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='vnpay_transaction_id',
            new_name='vnpay_transaction_no',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='vnpay_order_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='vnpay_bank_code',
            field=models.CharField(blank=True, help_text='Mã ngân hàng VNPay', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='vnpay_card_type',
            field=models.CharField(blank=True, help_text='Loại thẻ VNPay', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='vnpay_order_info',
            field=models.CharField(blank=True, help_text='Thông tin đơn hàng VNPay', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='vnpay_pay_date',
            field=models.CharField(blank=True, help_text='Ngày thanh toán VNPay', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='vnpay_txn_ref',
            field=models.CharField(blank=True, help_text='Mã giao dịch VNPay', max_length=50, null=True),
        ),
    ]
