# Generated by Django 5.2.1 on 2025-10-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_vnpay_transaction_id_payment_vnpay_transaction_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('vnpay', 'VNPay'), ('qr_code', 'QR Code')], default='vnpay', max_length=20),
        ),
    ]
