# Generated by Django 5.0.7 on 2025-10-15 12:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Court",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tên sân")),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "price_per_hour",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Giá/giờ",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="courts/",
                        verbose_name="Hình ảnh",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Sân",
                "verbose_name_plural": "Sân",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("06:00", "06:00 - 07:00"),
                            ("07:00", "07:00 - 08:00"),
                            ("08:00", "08:00 - 09:00"),
                            ("09:00", "09:00 - 10:00"),
                            ("10:00", "10:00 - 11:00"),
                            ("11:00", "11:00 - 12:00"),
                            ("12:00", "12:00 - 13:00"),
                            ("13:00", "13:00 - 14:00"),
                            ("14:00", "14:00 - 15:00"),
                            ("15:00", "15:00 - 16:00"),
                            ("16:00", "16:00 - 17:00"),
                            ("17:00", "17:00 - 18:00"),
                            ("18:00", "18:00 - 19:00"),
                            ("19:00", "19:00 - 20:00"),
                            ("20:00", "20:00 - 21:00"),
                            ("21:00", "21:00 - 22:00"),
                        ],
                        max_length=5,
                        unique=True,
                        verbose_name="Khung giờ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Khung giờ",
                "verbose_name_plural": "Khung giờ",
                "ordering": ["time"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Ngày đặt")),
                (
                    "total_hours",
                    models.PositiveIntegerField(default=1, verbose_name="Tổng số giờ"),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="Tổng tiền",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ xác nhận"),
                            ("confirmed", "Đã xác nhận"),
                            ("cancelled", "Đã hủy"),
                            ("completed", "Hoàn thành"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "payment_proof",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="payment_proofs/",
                        verbose_name="Minh chứng thanh toán",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Khách hàng",
                    ),
                ),
                (
                    "court",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="booking.court",
                        verbose_name="Sân",
                    ),
                ),
                (
                    "time_slots",
                    models.ManyToManyField(
                        to="booking.timeslot", verbose_name="Khung giờ"
                    ),
                ),
            ],
            options={
                "verbose_name": "Đơn đặt sân",
                "verbose_name_plural": "Đơn đặt sân",
                "ordering": ["-created_at"],
            },
        ),
    ]
