# Generated by Django 5.2.1 on 2025-10-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hạn thanh toán'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_required',
            field=models.BooleanField(default=True, verbose_name='Yêu cầu thanh toán'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('confirmed', 'Đã xác nhận'), ('cancelled', 'Đã hủy'), ('completed', 'Hoàn thành')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
